from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import os
from dotenv import load_dotenv
from groq import Groq
from models import FIRRequest

load_dotenv()

app = FastAPI(title="FIR Generator API")

# CORS setup
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # For development, allow all. Restrict in production.
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Groq Client
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
if not GROQ_API_KEY:
    print("Warning: GROQ_API_KEY not found in environment variables.")

client = Groq(api_key=GROQ_API_KEY)

from utils import load_ipc_data, get_relevant_sections

# Load IPC Data into memory on startup
load_ipc_data()

@app.post("/api/generate_fir")
async def generate_fir(request: FIRRequest):
    try:
        # Retrieve Relevant Laws based on case description
        relevant_laws = get_relevant_sections(request.case_description)
        print(f"Context injected: {len(relevant_laws)} chars")

        # Construct the prompt based on user requirements
        complainant_info = f"Name: {request.complainant.name}, Address: {request.complainant.address}, Contact: {request.complainant.contact}"
        accused_info = f"Name: {request.accused.name if request.accused else 'Unknown person(s)'}, Address: {request.accused.address if request.accused else 'Not provided'}"
        
        # New Official Info
        official_info = f"""
        Investigating Officer: {request.officer_name} ({request.officer_rank})
        """
        
        # --- STEP 1: SEMANTIC QUERY EXPANSION ---
        # Ask LLM to identify potential IPC sections and legal terms from the informal description
        # This acts as a bridge between "User Language" and "Legal Language"
        expansion_prompt = f"""
        Analyze this criminal case description and list the top 5 most relevant Indian Penal Code (IPC) Section Numbers and Legal Keywords.
        Return ONLY a comma-separated list.
        
        Case: "{request.case_description}"
        
        Example Output: Section 378, Theft, Section 379, Movable Property, Dishonest Intention
        """
        
        expansion_completion = client.chat.completions.create(
            messages=[{"role": "user", "content": expansion_prompt}],
            model="llama-3.3-70b-versatile",
            temperature=0.1,
            max_tokens=50
        )
        legal_keywords = expansion_completion.choices[0].message.content
        print(f"Semantic Expansion: {legal_keywords}")
        
        # --- STEP 2: RETRIEVAL ---
        # Combine user description with expert keywords for a rich search query
        search_query = f"{request.case_description} {legal_keywords}"
        relevant_laws = get_relevant_sections(search_query)
        print(f"Context injected: {len(relevant_laws)} chars")
        
        system_prompt = f"""You are an expert Indian Police Officer and Legal Drafting Assistant with deep knowledge of the Indian Penal Code (IPC) and standard FIR drafting procedures.

Your task is to convert informal user-provided case details into a legally structured First Information Report (FIR).

Here is the Reference IPC (Indian Penal Code) Law Data for your knowledge. Use this to explicitly cite the correct sections:
<LEGAL_CONTEXT>
{relevant_laws}
</LEGAL_CONTEXT>

STRICTLY FOLLOW THE FIR FORMAT BELOW:

-------------------------------
FIRST INFORMATION REPORT (FIR)
-------------------------------

1. Police Station: <Police Station>
2. FIR Number: <FIR Number>
3. Date and Time of Registration: <Registration Date>

4. Complainant (Plaintiff) Details:
   Name: <Name>
   Address: <Address>
   Contact Details: <Contact>
   (If any field is missing, clearly write "Not provided")

5. Accused (Defendant) Details:
   (Mention name and address if provided, otherwise write "Unknown person(s)")

6. Date, Time, and Place of Occurrence:
   (Mention only if clearly stated in the case description, otherwise write "Not provided")

7. Sections of Law Applied:
   - IPC Section <number> – <title>
   (Briefly explain why this section applies based on the facts)

8. Facts of the Case:
   (Formally narrate the incident in third-person legal language using phrases like
   “It is alleged that…”, strictly based on the case description.)

9. Investigating Officer:
   Name: <Investigating Officer Name>
   Rank: <Rank>

10. Signature / Thumb Impression of Complainant: Not provided

MANDATORY DISCLAIMER (MUST BE INCLUDED AT THE END):
“This FIR has been generated by an AI system for academic and assistive purposes only and does not have legal validity unless reviewed and registered by authorized police officials.”
"""

        user_content = f"""
Input Details:
1. CONSTANT DETAILS (Use these exactly):
{official_info}

2. Complainant Details: {complainant_info}
3. Accused Details: {accused_info}
4. Case Description: {request.case_description}
5. Date/Time/Place Note: {request.date_time_place}
"""

        completion = client.chat.completions.create(
            messages=[
                {
                    "role": "system",
                    "content": system_prompt
                },
                {
                    "role": "user",
                    "content": user_content
                }
            ],
            model="llama-3.3-70b-versatile",
            temperature=0.3,
        )

        generated_fir = completion.choices[0].message.content
        return {"fir": generated_fir}

    except Exception as e:
        print(f"Error generating FIR: {str(e)}") # Log the error
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/")
def read_root():
    return {"message": "FIR Generator API is running"}
