import React, { useRef } from "react";
import { Download, Share2, Printer } from "lucide-react";
import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";

const FIRDisplay = ({ firText, language = "en" }) => {
    const contentRef = useRef(null);

    if (!firText) return null;

    const cleanFirText = (text) => {
        if (!text) return "";
        let cleaned = text;

        // Remove "Not provided" from signature line
        cleaned = cleaned.replace(
            /Signature \/ Thumb Impression of Complainant: Not provided/g,
            "Signature / Thumb Impression of Complainant:",
        );

        // Remove Mandatory Disclaimer block completely
        cleaned = cleaned.replace(
            /MANDATORY DISCLAIMER \(MUST BE INCLUDED AT THE END\):[\s\S]*?(\n\n|$)/g,
            "",
        );

        // Also remove the specific quote if it appears standalone
        cleaned = cleaned.replace(
            /“This FIR has been generated by an AI system.*?official authorities\.”/s,
            "",
        );

        // Remove dashed FIR Header block
        cleaned = cleaned.replace(
            /(-{3,})[\s\S]*?FIRST INFORMATION REPORT \(FIR\)[\s\S]*?(-{3,})/g,
            "",
        );

        return cleaned.trim();
    };

    const displayedText = cleanFirText(firText);

    const generatePDF = async (action = "download") => {
        if (!contentRef.current) return;

        try {
            const element = contentRef.current;

            const canvas = await html2canvas(element, {
                scale: 2,
                useCORS: true,
                logging: false,
                backgroundColor: "#ffffff",
            });

            const imgData = canvas.toDataURL("image/png");
            const pdf = new jsPDF("p", "mm", "a4");

            const pdfWidth = pdf.internal.pageSize.getWidth();
            const pdfHeight = pdf.internal.pageSize.getHeight();

            const imgWidth = pdfWidth;
            const imgHeight = (canvas.height * imgWidth) / canvas.width;

            let heightLeft = imgHeight;
            let position = 0;

            pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight);
            heightLeft -= pdfHeight;

            while (heightLeft >= 0) {
                position = heightLeft - imgHeight;
                pdf.addPage();
                pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight);
                heightLeft -= pdfHeight;
            }

            // Extract FIR Number for filename
            const firNumberMatch = firText.match(/FIR Number:[\s\t]*([^\n]*)/i);
            let firNumber = "Draft";
            if (
                firNumberMatch &&
                firNumberMatch[1] &&
                firNumberMatch[1].trim() !== "Not provided"
            ) {
                firNumber = firNumberMatch[1].trim();
            }
            const safeFirNumber = firNumber.replace(/[^a-z0-9\-_]/gi, "_");
            const filename = `FIR_${safeFirNumber}.pdf`;

            if (action === "download") {
                pdf.save(filename);
            } else if (action === "print") {
                pdf.autoPrint();
                window.open(pdf.output("bloburl"), "_blank");
            }
        } catch (err) {
            console.error("PDF Generation failed:", err);
            alert("Failed to generate PDF. Please try again.");
        }
    };

    return (
        <div className="bg-white p-8 rounded-xl shadow-lg border border-[#dccba0] legal-paper h-full flex flex-col">
            <div className="flex justify-between items-start mb-6 border-b border-[#dccba0] pb-4">
                <div>
                    <h2 className="text-2xl font-bold font-serif text-black">
                        FIR Preview
                    </h2>
                    <p className="text-[#8b7d5b] text-sm mt-1">
                        Generated Draft • Non-Legally Binding
                    </p>
                </div>
                <div className="flex gap-2">
                    <button
                        onClick={() => generatePDF("print")}
                        className="p-2 hover:bg-[#f4f0e6] rounded-full text-[#1a3c6e] transition-colors"
                        title="Print"
                    >
                        <Printer className="w-5 h-5" />
                    </button>
                    <button
                        onClick={() => generatePDF("download")}
                        className="p-2 hover:bg-[#f4f0e6] rounded-full text-[#1a3c6e] transition-colors"
                        title="Download"
                    >
                        <Download className="w-5 h-5" />
                    </button>
                </div>
            </div>

            <div className="flex-1 overflow-auto pr-4 custom-scrollbar">
                {/* Render formatted FIR content wrapped in a div for capture */}
                <div
                    ref={contentRef}
                    className="font-serif text-[#0a1629] whitespace-pre-wrap leading-relaxed print-content bg-white p-4"
                >
                    {/* Header explicitly included for PDF capture */}
                    <div className="text-center font-bold text-xl mb-6 underline">
                        FIRST INFORMATION REPORT
                    </div>

                    {displayedText.split("\n").map((line, index) => {
                        if (line.includes(":")) {
                            const parts = line.split(":");
                            if (parts.length > 1 && parts[0].length < 50) {
                                return (
                                    <div key={index} className="mb-1">
                                        <span className="font-semibold text-gray-800">
                                            {parts[0]}:
                                        </span>
                                        <span>{parts.slice(1).join(":")}</span>
                                    </div>
                                );
                            }
                        }
                        return (
                            <div key={index} className="mb-1">
                                {line}
                            </div>
                        );
                    })}

                    <div className="mt-8 pt-8 border-t border-dashed border-gray-400">
                        <p className="text-right font-bold">
                            Signature of Officer In-Charge
                        </p>
                    </div>
                </div>
            </div>

            <style jsx>{`
                .custom-scrollbar::-webkit-scrollbar {
                    width: 8px;
                }
                .custom-scrollbar::-webkit-scrollbar-track {
                    background: #f4f0e6;
                }
                .custom-scrollbar::-webkit-scrollbar-thumb {
                    background: #1a3c6e;
                    border-radius: 4px;
                }

                @media print {
                    body * {
                        visibility: hidden;
                    }
                    .legal-paper,
                    .legal-paper * {
                        visibility: visible;
                    }
                    .legal-paper {
                        position: absolute;
                        left: 0;
                        top: 0;
                        width: 100%;
                        margin: 0;
                        padding: 20px;
                        background: white !important;
                        box-shadow: none !important;
                        border: none !important;
                    }
                    .print\:hidden,
                    button {
                        display: none !important;
                    }
                    .print-content {
                        font-size: 12pt;
                        color: black !important;
                        height: auto;
                        overflow: visible;
                    }
                }
            `}</style>
        </div>
    );
};

export default FIRDisplay;
