import React from 'react';
import { Download, Share2, Printer } from 'lucide-react';

const FIRDisplay = ({ firText }) => {
  if (!firText) return null;

  return (
    <div className="bg-white p-8 rounded-xl shadow-lg border border-[#dccba0] legal-paper h-full flex flex-col">
      <div className="flex justify-between items-start mb-6 border-b border-[#dccba0] pb-4">
        <div>
          <h2 className="text-2xl font-bold font-serif text-[#1a3c6e]">FIR Preview</h2>
          <p className="text-[#8b7d5b] text-sm mt-1">Generated Draft • Non-Legally Binding</p>
        </div>
        <div className="flex gap-2">
          <button className="p-2 hover:bg-[#f4f0e6] rounded-full text-[#1a3c6e] transition-colors" title="Print" onClick={() => window.print()}>
            <Printer className="w-5 h-5" />
          </button>
          <button className="p-2 hover:bg-[#f4f0e6] rounded-full text-[#1a3c6e] transition-colors" title="Download">
            <Download className="w-5 h-5" />
          </button>
        </div>
      </div>

      <div className="flex-1 overflow-auto pr-4 custom-scrollbar">
        {/* Render formatted FIR content */}
        <div className="font-serif text-[#0a1629] whitespace-pre-wrap leading-relaxed print-content">
          {firText.split('\n').map((line, index) => {
            // Check for bold headings (numbered items or headers)
            if (/^\d+\./.test(line.trim()) || line.trim().startsWith('FIRST INFORMATION REPORT') || line.trim().startsWith('MANDATORY DISCLAIMER')) {
              return <div key={index} className="font-bold text-[#1a3c6e] mt-4 mb-2 text-lg">{line}</div>;
            }
            // Check for key-value pairs to bold keys
            if (line.includes(':')) {
                const parts = line.split(':');
                if (parts.length > 1 && parts[0].length < 50) { // Simple heuristic
                    return (
                        <div key={index} className="mb-1">
                            <span className="font-semibold text-gray-800">{parts[0]}:</span>
                            <span>{parts.slice(1).join(':')}</span>
                        </div>
                    );
                }
            }
            return <div key={index} className="mb-1">{line}</div>;
          })}
        </div>
      </div>

      <div className="mt-6 pt-4 border-t border-[#dccba0] text-center print:hidden">
        <p className="text-xs text-[#d0b87d] italic">
          Draft generated by AI. Verify with official authorities before use.
        </p>
      </div>

      <style jsx>{`
        .custom-scrollbar::-webkit-scrollbar {
          width: 8px;
        }
        .custom-scrollbar::-webkit-scrollbar-track {
          background: #f4f0e6;
        }
        .custom-scrollbar::-webkit-scrollbar-thumb {
          background: #1a3c6e;
          border-radius: 4px;
        }
        
        @media print {
            body * {
                visibility: hidden;
            }
            .legal-paper, .legal-paper * {
                visibility: visible;
            }
            .legal-paper { 
                position: absolute;
                left: 0;
                top: 0;
                width: 100%;
                margin: 0;
                padding: 20px;
                background: white !important; 
                box-shadow: none !important;
                border: none !important;
                background-image: none !important; /* Remove dots */
            }
            .print\:hidden, button {
                display: none !important;
            }
            .print-content {
                font-size: 12pt;
                color: black !important;
                height: auto;
                overflow: visible;
            }
            .custom-scrollbar {
                overflow: visible;
            }
        }
      `}</style>
    </div>
  );
};

export default FIRDisplay;
